version: "3"

services:
  database:
    build: ./db
    container_name: miso-database
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: {}
